#command for all table size

SELECT 'abandoned_cart_items' as table_name, COUNT(*) as row_count FROM abandoned_cart_items
UNION ALL SELECT 'abandoned_cart_metas', COUNT(*) FROM abandoned_cart_metas
UNION ALL SELECT 'abandoned_carts', COUNT(*) FROM abandoned_carts
UNION ALL SELECT 'activity_log', COUNT(*) FROM activity_log
UNION ALL SELECT 'addons', COUNT(*) FROM addons
UNION ALL SELECT 'agent_assign_logs', COUNT(*) FROM agent_assign_logs
UNION ALL SELECT 'agent_status_logs', COUNT(*) FROM agent_status_logs
UNION ALL SELECT 'agents', COUNT(*) FROM agents
UNION ALL SELECT 'announce_target_audience', COUNT(*) FROM announce_target_audience
UNION ALL SELECT 'announcements', COUNT(*) FROM announcements
UNION ALL SELECT 'app_access_tokens', COUNT(*) FROM app_access_tokens
UNION ALL SELECT 'applied_coupons', COUNT(*) FROM applied_coupons
UNION ALL SELECT 'attributes', COUNT(*) FROM attributes
UNION ALL SELECT 'bills', COUNT(*) FROM bills
UNION ALL SELECT 'blocked_ips', COUNT(*) FROM blocked_ips
UNION ALL SELECT 'blocked_numbers', COUNT(*) FROM blocked_numbers
UNION ALL SELECT 'brand_product', COUNT(*) FROM brand_product
UNION ALL SELECT 'brands', COUNT(*) FROM brands
UNION ALL SELECT 'cache', COUNT(*) FROM cache
UNION ALL SELECT 'cache_locks', COUNT(*) FROM cache_locks
UNION ALL SELECT 'call_automation_logs', COUNT(*) FROM call_automation_logs
UNION ALL SELECT 'call_automation_settings', COUNT(*) FROM call_automation_settings
UNION ALL SELECT 'call_automations', COUNT(*) FROM call_automations
UNION ALL SELECT 'call_balances', COUNT(*) FROM call_balances
UNION ALL SELECT 'call_center_agent_logs', COUNT(*) FROM call_center_agent_logs
UNION ALL SELECT 'call_center_agents', COUNT(*) FROM call_center_agents
UNION ALL SELECT 'call_center_subscriptions', COUNT(*) FROM call_center_subscriptions
UNION ALL SELECT 'call_configurations', COUNT(*) FROM call_configurations
UNION ALL SELECT 'call_histories', COUNT(*) FROM call_histories
UNION ALL SELECT 'call_initiation_logs', COUNT(*) FROM call_initiation_logs
UNION ALL SELECT 'caller_id_forms', COUNT(*) FROM caller_id_forms
UNION ALL SELECT 'calling_agent_emails', COUNT(*) FROM calling_agent_emails
UNION ALL SELECT 'cancel_reasons', COUNT(*) FROM cancel_reasons
UNION ALL SELECT 'comments', COUNT(*) FROM comments
UNION ALL SELECT 'contacts', COUNT(*) FROM contacts
UNION ALL SELECT 'coupons', COUNT(*) FROM coupons
UNION ALL SELECT 'couriers', COUNT(*) FROM couriers
UNION ALL SELECT 'custom_prices', COUNT(*) FROM custom_prices
UNION ALL SELECT 'custom_sms_texts', COUNT(*) FROM custom_sms_texts
UNION ALL SELECT 'customer_coupons', COUNT(*) FROM customer_coupons
UNION ALL SELECT 'customers', COUNT(*) FROM customers
UNION ALL SELECT 'dns_records', COUNT(*) FROM dns_records
UNION ALL SELECT 'domains', COUNT(*) FROM domains
UNION ALL SELECT 'ecommerce_banners', COUNT(*) FROM ecommerce_banners
UNION ALL SELECT 'ecommerce_pages', COUNT(*) FROM ecommerce_pages
UNION ALL SELECT 'ecommerce_settings', COUNT(*) FROM ecommerce_settings
UNION ALL SELECT 'exports', COUNT(*) FROM exports
UNION ALL SELECT 'facebook_settings', COUNT(*) FROM facebook_settings
UNION ALL SELECT 'failed_import_rows', COUNT(*) FROM failed_import_rows
UNION ALL SELECT 'failed_jobs', COUNT(*) FROM failed_jobs
UNION ALL SELECT 'fake_order_settings', COUNT(*) FROM fake_order_settings
UNION ALL SELECT 'google_settings', COUNT(*) FROM google_settings
UNION ALL SELECT 'imports', COUNT(*) FROM imports
UNION ALL SELECT 'invitations', COUNT(*) FROM invitations
UNION ALL SELECT 'invoice_settings', COUNT(*) FROM invoice_settings
UNION ALL SELECT 'job_batches', COUNT(*) FROM job_batches
UNION ALL SELECT 'jobs', COUNT(*) FROM jobs
UNION ALL SELECT 'microsoft_settings', COUNT(*) FROM microsoft_settings
UNION ALL SELECT 'migrations', COUNT(*) FROM migrations
UNION ALL SELECT 'notifications', COUNT(*) FROM notifications
UNION ALL SELECT 'order_items', COUNT(*) FROM order_items
UNION ALL SELECT 'order_logs', COUNT(*) FROM order_logs
UNION ALL SELECT 'order_metas', COUNT(*) FROM order_metas
UNION ALL SELECT 'orders', COUNT(*) FROM orders
UNION ALL SELECT 'page_drafts', COUNT(*) FROM page_drafts
UNION ALL SELECT 'page_settings', COUNT(*) FROM page_settings
UNION ALL SELECT 'page_views', COUNT(*) FROM page_views
UNION ALL SELECT 'pages', COUNT(*) FROM pages
UNION ALL SELECT 'password_reset_tokens', COUNT(*) FROM password_reset_tokens
UNION ALL SELECT 'payment_settings', COUNT(*) FROM payment_settings
UNION ALL SELECT 'payments', COUNT(*) FROM payments
UNION ALL SELECT 'permission_role', COUNT(*) FROM permission_role
UNION ALL SELECT 'permissions', COUNT(*) FROM permissions
UNION ALL SELECT 'personal_access_tokens', COUNT(*) FROM personal_access_tokens
UNION ALL SELECT 'product_categories', COUNT(*) FROM product_categories
UNION ALL SELECT 'product_product_category', COUNT(*) FROM product_product_category
UNION ALL SELECT 'products', COUNT(*) FROM products
UNION ALL SELECT 'purchased_addons', COUNT(*) FROM purchased_addons
UNION ALL SELECT 'role_user', COUNT(*) FROM role_user
UNION ALL SELECT 'roles', COUNT(*) FROM roles
UNION ALL SELECT 'sales', COUNT(*) FROM sales
UNION ALL SELECT 'sales_target_histories', COUNT(*) FROM sales_target_histories
UNION ALL SELECT 'sales_targets', COUNT(*) FROM sales_targets
UNION ALL SELECT 'sample_page_categories', COUNT(*) FROM sample_page_categories
UNION ALL SELECT 'sample_page_sample_page_category', COUNT(*) FROM sample_page_sample_page_category
UNION ALL SELECT 'sample_pages', COUNT(*) FROM sample_pages
UNION ALL SELECT 'seller_payments', COUNT(*) FROM seller_payments
UNION ALL SELECT 'sessions', COUNT(*) FROM sessions
UNION ALL SELECT 'shop_settings', COUNT(*) FROM shop_settings
UNION ALL SELECT 'shop_user', COUNT(*) FROM shop_user
UNION ALL SELECT 'shop_user_logs', COUNT(*) FROM shop_user_logs
UNION ALL SELECT 'shops', COUNT(*) FROM shops
UNION ALL SELECT 'site_settings', COUNT(*) FROM site_settings
UNION ALL SELECT 'sites', COUNT(*) FROM sites
UNION ALL SELECT 'sms', COUNT(*) FROM sms
UNION ALL SELECT 'sms_balances', COUNT(*) FROM sms_balances
UNION ALL SELECT 'sms_configurations', COUNT(*) FROM sms_configurations
UNION ALL SELECT 'sms_settings', COUNT(*) FROM sms_settings
UNION ALL SELECT 'sms_templates', COUNT(*) FROM sms_templates
UNION ALL SELECT 'stock_histories', COUNT(*) FROM stock_histories
UNION ALL SELECT 'stocks', COUNT(*) FROM stocks
UNION ALL SELECT 'subscription_histories', COUNT(*) FROM subscription_histories
UNION ALL SELECT 'subscriptions', COUNT(*) FROM subscriptions
UNION ALL SELECT 'super_permission_super_role', COUNT(*) FROM super_permission_super_role
UNION ALL SELECT 'super_permissions', COUNT(*) FROM super_permissions
UNION ALL SELECT 'super_role_user', COUNT(*) FROM super_role_user
UNION ALL SELECT 'super_roles', COUNT(*) FROM super_roles
UNION ALL SELECT 'telescope_entries', COUNT(*) FROM telescope_entries
UNION ALL SELECT 'telescope_entries_tags', COUNT(*) FROM telescope_entries_tags
UNION ALL SELECT 'telescope_monitoring', COUNT(*) FROM telescope_monitoring
UNION ALL SELECT 'tiktok_settings', COUNT(*) FROM tiktok_settings
UNION ALL SELECT 'tutorial_categories', COUNT(*) FROM tutorial_categories
UNION ALL SELECT 'tutorials', COUNT(*) FROM tutorials
UNION ALL SELECT 'users', COUNT(*) FROM users
UNION ALL SELECT 'variants', COUNT(*) FROM variants
UNION ALL SELECT 'webhooks', COUNT(*) FROM webhooks
UNION ALL SELECT 'woocommerce_settings', COUNT(*) FROM woocommerce_settings;